"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Item={id:string;name:string;short:string;x:number;y:number;kind:"hazard"|"decoy"};
type Level={name:string;area:string;image:string;items:Item[]};

const hazardDetails:Record<string,string>={
 "Overloaded power strip":"Power strips have a maximum electrical load. Several devices—especially heaters, entertainment equipment, or chargers—can make the strip and its connections dangerously hot without tripping right away.",
 "Damaged cord under the rug":"Walking and furniture can crush the cord while the rug hides warning signs. The rug also holds heat against the damaged insulation.",
 "Loose outlet":"Movement can loosen electrical connections behind the wall. Loose connections may create heat or arcing even when the outlet still appears to work.",
 "Space heater on an extension cord":"Portable heaters draw a lot of power for long periods. Many extension cords and power strips are not designed to safely carry that load.",
 "Missing outlet cover":"The cover helps keep fingers and objects away from the wiring and metal parts around the receptacle. This is especially important where children play.",
 "Damaged appliance cord":"Cracked or split insulation can expose the conductors inside. Continued use may cause shock, heat, or arcing near a countertop.",
 "No visible GFCI protection":"GFCI protection is designed to shut power off quickly when current takes an unintended path, such as through water or a person.",
 "Overloaded appliance connection":"Toasters, kettles, microwaves, and similar appliances can each use substantial power. Combining them on one connection may overheat plugs, cords, or receptacles.",
 "Pinched extension cord":"A refrigerator can slowly crush a cord against the wall or floor. The damage may remain hidden while the appliance continues operating.",
 "Overheated receptacle":"Brown marks, melting, buzzing, or unusual warmth can point to a loose connection or excessive load behind the outlet.",
 "Uncovered junction box":"The box and cover contain sparks and keep people and stored objects away from wire connections. Exposed splices should not be left accessible.",
 "Extension cord as permanent wiring":"Flexible cords are made for temporary use and are more easily damaged than installed wiring. They should not run through walls, ceilings, or doorways as a permanent solution.",
 "Electrical equipment near water":"Leaks and puddles can create a path for electricity. Basements need suitable spacing, equipment, and protective devices for damp locations.",
 "Crowded, poorly labeled panel":"A panel should be accessible and accurately identified so circuits can be shut off quickly. Crowding also makes inspection and safe service harder.",
 "Improper taped cord repair":"Electrical tape can loosen, wear through, or conceal damage. It does not restore the cord's original insulation or strain protection.",
 "Exposed charging wire":"Small charging cables still carry electrical energy and can overheat at a damaged spot. Stop using a cable when the insulation or connector is failing.",
 "Power strip under bedding":"Blankets and mattresses trap heat and can press plugs partly out of their sockets. Power equipment needs ventilation and a visible, open location.",
 "Heater too close to curtains":"Curtains can move into the heater or become hot over time. Portable heaters need a clear safety zone on every side.",
 "Improper two-prong adapter":"A three-prong adapter does not automatically add a safe grounding path. The correct solution depends on the home's wiring and protection.",
 "Damaged light-fixture wiring":"Flickering, heat, buzzing, or visible conductor damage can indicate a loose or failing connection above the fixture.",
 "Indoor extension cord outside":"Indoor cords may lack the weather, sunlight, and abrasion resistance required outdoors. Moisture can enter damaged insulation or plug connections.",
 "Damaged outdoor outlet cover":"A cracked or missing cover lets rain and debris reach the receptacle. Outdoor covers must remain protective even while appropriate cords are connected.",
 "Damaged string-light wiring":"Outdoor decorations are repeatedly moved and weathered. Cracked sockets or insulation can expose live parts along the entire light string.",
 "Electrical equipment in standing water":"Water can energize nearby surfaces and greatly increase shock risk. Keep people away and have the source made safe by a qualified professional.",
 "Overloaded outdoor connection":"Stacked adapters and multiple plugs can exceed the connection's rating and defeat its weather protection, allowing both heat and moisture problems."
};

const levels:Level[]=[
 {name:"South Philly Living Room",area:"A warm rowhome mystery",image:"/scene-south-philly.png",items:[
  {id:"strip",name:"Overloaded power strip",short:"Too many plugs can overheat a power strip. Spread the load and have the setup checked.",x:76,y:82,kind:"hazard"},
  {id:"rug",name:"Damaged cord under the rug",short:"Rugs hide cord damage and trap heat where nobody can see it.",x:32,y:95,kind:"hazard"},
  {id:"outlet",name:"Loose outlet",short:"An outlet pulling from the wall can expose energized parts.",x:55.5,y:41,kind:"hazard"},
  {id:"heater",name:"Space heater on an extension cord",short:"Space heaters should plug directly into a proper wall outlet.",x:88,y:61,kind:"hazard"},
  {id:"cover",name:"Missing outlet cover",short:"A missing cover leaves wiring within easy reach—especially for children.",x:4,y:70,kind:"hazard"},
  {id:"wrapper",name:"Cheesesteak wrapper",short:"Greasy? Yes. Electrical hazard? Not today.",x:53,y:56,kind:"decoy"},{id:"radiator",name:"Old radiator",short:"Oggi says: warm, clanky, and innocent.",x:88,y:48,kind:"decoy"},{id:"art",name:"Crooked artwork",short:"A decorating mystery, not an electrical one.",x:31,y:23,kind:"decoy"}]},
 {name:"West Philly Kitchen",area:"Colorful, cozy & suspicious",image:"/scene-west-philly.png",items:[
  {id:"cord",name:"Damaged appliance cord",short:"A split appliance cord can expose energized wiring.",x:23.2,y:55.5,kind:"hazard"},{id:"gfci",name:"No visible GFCI protection",short:"Kitchen outlets near water need proper shock protection.",x:32.2,y:42,kind:"hazard"},{id:"appliances",name:"Overloaded appliance connection",short:"High-wattage kitchen appliances should not crowd one connection.",x:35.2,y:48.7,kind:"hazard"},{id:"fridge",name:"Pinched extension cord",short:"A cord pinched behind an appliance can quietly break down.",x:16.1,y:62.5,kind:"hazard"},{id:"heat",name:"Overheated receptacle",short:"Darkening or heat marks around an outlet deserve prompt attention.",x:66,y:38.8,kind:"hazard"},{id:"plant",name:"Dramatic houseplant",short:"Droopy leaves? Maybe. Dangerous wiring? Nope.",x:12,y:31,kind:"decoy"},{id:"mug",name:"World's largest mug",short:"Suspiciously huge, electrically harmless.",x:62,y:38,kind:"decoy"},{id:"bike",name:"Bicycle outside",short:"Fast transportation—not faulty wiring.",x:82,y:25,kind:"decoy"}]},
 {name:"Northeast Philly Basement",area:"Clutter hides clues",image:"/scene-northeast-basement.png",items:[
  {id:"box",name:"Uncovered junction box",short:"Junction boxes need covers to keep wiring safely enclosed.",x:93,y:30,kind:"hazard"},{id:"permanent",name:"Extension cord as permanent wiring",short:"Extension cords are temporary—not a substitute for installed wiring.",x:55,y:6,kind:"hazard"},{id:"water",name:"Electrical equipment near water",short:"Electricity and wet areas need careful separation and protection.",x:66,y:73,kind:"hazard"},{id:"panel",name:"Crowded, poorly labeled panel",short:"A clear, accessible, properly labeled panel helps make a home safer.",x:78,y:31,kind:"hazard"},{id:"tape",name:"Improper taped cord repair",short:"Tape alone does not restore a damaged cord's safety.",x:89,y:34,kind:"hazard"},{id:"ball",name:"Vintage basketball",short:"Flat? Probably. Electrically dangerous? No.",x:13,y:79,kind:"decoy"},{id:"sock",name:"Runaway sock",short:"A laundry fugitive. Oggi will investigate separately.",x:57,y:80,kind:"decoy"},{id:"box2",name:"Mystery storage box",short:"Full of holiday lights—not currently plugged in.",x:64,y:31,kind:"decoy"}]},
 {name:"Mount Airy Bedroom",area:"A cozy old-home case",image:"/scene-mount-airy.png",items:[
  {id:"charge",name:"Exposed charging wire",short:"A frayed charging cable can shock, spark, or overheat.",x:27,y:94,kind:"hazard"},{id:"bedding",name:"Power strip under bedding",short:"Bedding traps heat around power strips and plugs.",x:64,y:83,kind:"hazard"},{id:"curtain",name:"Heater too close to curtains",short:"Portable heaters need plenty of open space from anything that can burn.",x:32,y:55,kind:"hazard"},{id:"adapter",name:"Improper two-prong adapter",short:"An adapter does not create the grounding protection an outlet lacks.",x:86,y:92,kind:"hazard"},{id:"fixture",name:"Damaged light-fixture wiring",short:"Flickering plus visible damage is a clue to stop using the fixture and call a pro.",x:49,y:7,kind:"hazard"},{id:"books",name:"Leaning book tower",short:"A plot twist, not a power problem.",x:15,y:51,kind:"decoy"},{id:"slippers",name:"Fuzzy slippers",short:"Oggi approves. Zero volts detected.",x:61,y:83,kind:"decoy"},{id:"portrait",name:"Serious portrait",short:"Judgmental? Yes. Electrically suspicious? No.",x:34,y:25,kind:"decoy"}]},
 {name:"Philly Backyard & Rooftop",area:"One last outdoor sniff",image:"/scene-philly-rooftop.png",items:[
  {id:"indoor",name:"Indoor extension cord outside",short:"Indoor cords are not built to handle outdoor moisture and wear.",x:18,y:91,kind:"hazard"},{id:"cover",name:"Damaged outdoor outlet cover",short:"Outdoor receptacles need an intact weather-resistant cover.",x:14,y:37,kind:"hazard"},{id:"lights",name:"Damaged string-light wiring",short:"Cracked or exposed light wiring should be taken out of service.",x:46.5,y:14.5,kind:"hazard"},{id:"puddle",name:"Electrical equipment in standing water",short:"Unplugged or not, electrical equipment does not belong in standing water.",x:67,y:88,kind:"hazard"},{id:"overload",name:"Overloaded outdoor connection",short:"Stacked outdoor plugs can overheat and lose weather protection.",x:32.5,y:79,kind:"hazard"},{id:"gnome",name:"Tiny rowhome gnome",short:"Suspicious mustache. Safe wiring.",x:16,y:69,kind:"decoy"},{id:"tomato",name:"Champion tomato",short:"Oggi found a snack, not a hazard.",x:89,y:54,kind:"decoy"},{id:"chair",name:"Upside-down patio chair",short:"Wind did it. Case closed.",x:82,y:78,kind:"decoy"}]}
];

function Oggi({mood="ready"}:{mood?:string}){return <div className={`oggi oggi-${mood}`} aria-label={`Oggi is ${mood}`}><span className="ear left"/><span className="ear right"/><span className="face"><i className="blaze"/><b className="eye e1"/><b className="eye e2"/><em className="muzzle">●</em></span><span className="collar"/><span className="tag">⚡</span></div>}

export default function Home(){
 const [screen,setScreen]=useState<"start"|"map"|"game"|"levelEnd"|"final">("start"),[level,setLevel]=useState(0),[found,setFound]=useState<string[]>([]),[seenDecoys,setSeenDecoys]=useState<string[]>([]),[score,setScore]=useState(0),[time,setTime]=useState(90),[hints,setHints]=useState(3),[paused,setPaused]=useState(false),[sound,setSound]=useState(true),[message,setMessage]=useState(""),[mood,setMood]=useState("ready"),[scale,setScale]=useState(1),[offset,setOffset]=useState({x:0,y:0});
 const unlocked=Number(typeof window!=="undefined"?localStorage.getItem("oggi-unlocked")||0:0); const stage=useRef<HTMLDivElement>(null); const drag=useRef<any>(null); const pointers=useRef(new Map<number,{x:number,y:number}>()); const pinch=useRef<any>(null); const active=levels[level];
 useEffect(()=>{if(screen!=="game"||paused||message)return; const t=setInterval(()=>setTime(v=>{if(v<=1){clearInterval(t);setMood("hiding");setScreen("levelEnd");return 0}if(v===16)setMood("worried");return v-1}),1000);return()=>clearInterval(t)},[screen,paused,message]);
 useEffect(()=>{document.body.style.overflow=screen==="game"?"hidden":"auto";document.body.style.touchAction=screen==="game"?"none":"auto";return()=>{document.body.style.overflow="auto";document.body.style.touchAction="auto"}},[screen]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(screen!=="game")return;if(e.key==="ArrowLeft")setOffset(v=>({...v,x:v.x+28}));if(e.key==="ArrowRight")setOffset(v=>({...v,x:v.x-28}));if(e.key==="ArrowUp")setOffset(v=>({...v,y:v.y+28}));if(e.key==="ArrowDown")setOffset(v=>({...v,y:v.y-28}));if(e.key==="+"||e.key==="=")setScale(s=>Math.min(2,s+.25));if(e.key==="-")setScale(s=>Math.max(1,s-.25));if(e.key.toLowerCase()==="h")hint()};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)});
 const beep=(good=true)=>{if(!sound)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=good?660:180;g.gain.setValueAtTime(.08,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.22);o.start();o.stop(a.currentTime+.22)}catch{}};
 const begin=(i=0)=>{setLevel(i);setFound([]);setSeenDecoys([]);setScore(0);setTime(90);setHints(3);setPaused(false);setMessage("");setMood("ready");setScale(1);setOffset({x:0,y:0});setScreen("game")};
 const closeMessage=()=>{const completed=found.length===5&&!message.startsWith("Oggi's");setMessage("");setMood("ready");if(completed)setScreen("levelEnd")};
 const inspect=(item:Item)=>{if(paused||message)return;if(item.kind==="hazard"){if(found.includes(item.id))return;setFound(v=>[...v,item.id]);setScore(s=>s+200+time*2);setMood("found");setMessage(item.name+"|"+item.short+"|"+hazardDetails[item.name]);beep()}else{if(seenDecoys.includes(item.id))return;setSeenDecoys(v=>[...v,item.id]);setScore(s=>Math.max(0,s-35));setMood("confused");setMessage(item.name+"|"+item.short);beep(false);setTimeout(()=>{setMessage("");setMood("ready")},2600)}};
 const hint=()=>{if(!hints||message)return;const item=active.items.find(i=>i.kind==="hazard"&&!found.includes(i.id));if(!item)return;setHints(h=>h-1);setScore(s=>Math.max(0,s-75));setMood("point");setMessage("Oggi's nose is twitching…|Look near the pulsing orange search ring!");document.documentElement.style.setProperty("--hint-x",item.x+"%");document.documentElement.style.setProperty("--hint-y",item.y+"%");stage.current?.classList.add("hinting");setTimeout(()=>{stage.current?.classList.remove("hinting");setMessage("");setMood("ready")},1800)};
 const pointerDown=(e:any)=>{pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});e.currentTarget.setPointerCapture(e.pointerId);if(pointers.current.size===1)drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y};if(pointers.current.size===2){const p=[...pointers.current.values()];pinch.current={d:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),s:scale}}};const pointerMove=(e:any)=>{if(!pointers.current.has(e.pointerId))return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size===2&&pinch.current){const p=[...pointers.current.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);setScale(Math.max(1,Math.min(2,pinch.current.s*d/pinch.current.d)));return}if(drag.current?.id===e.pointerId)setOffset({x:drag.current.ox+e.clientX-drag.current.x,y:drag.current.oy+e.clientY-drag.current.y})};const pointerUp=(e:any)=>{pointers.current.delete(e.pointerId);drag.current=null;pinch.current=null};
 const finish=()=>{const next=Math.min(4,level+1);localStorage.setItem("oggi-unlocked",String(Math.max(unlocked,next)));if(level===4)setScreen("final");else setScreen("map")};
 const paws=found.length<5?1:(time>=35&&hints===3&&seenDecoys.length<=1?3:2);const badge=score>1600?"Oggi’s Top Inspector":score>1250?"Hazard Hound":score>900?"Rowhome Rescuer":level>1?"Circuit Detective":"Safety Sniffer";const selectedItem=active.items.find(item=>item.name===message.split("|")[0]);

 if(screen==="start")return <main className="start"><div className="skyline"/><div className="brand">GEN<span>3</span> <small>ELECTRIC & HVAC</small></div><section className="start-card"><div className="casefile">PHILLY CASE FILE • 001</div><Oggi mood="jump"/><p className="eyebrow">A HIDDEN-OBJECT ADVENTURE</p><h1>Can You Sniff Out<br/><em>the Hazards?</em></h1><p>Explore each Philly home with Oggi. Find five hidden electrical hazards before time runs out—but watch out for harmless decoys!</p><button className="primary" onClick={()=>setScreen("map")}>Start the Inspection <b>→</b></button><div className="mini-features"><span>◉ 5 Philly homes</span><span>⏱ 90-second cases</span><span>🐾 Oggi hints</span></div></section></main>;
 if(screen==="map")return <main className="map"><header><div className="brand">GEN<span>3</span></div><div><small>OGGI’S CASEBOOK</small><h1>Choose the next case</h1></div></header><div className="route">{levels.map((l,i)=><button key={l.name} disabled={i>Math.max(unlocked,level)} onClick={()=>begin(i)} className={i<=Math.max(unlocked,level)?"open":"locked"}><span className="map-num">{i>Math.max(unlocked,level)?"🔒":i+1}</span><div><b>{l.name}</b><small>{l.area}</small></div><em>{i<level?"🐾🐾":"→"}</em></button>)}</div><Oggi mood="point"/></main>;
 if(screen==="levelEnd"){const all=found.length===5;return <main className="end"><div className="confetti">✦　●　✦　●　✦</div><Oggi mood={all?"jump":"hiding"}/><p className="eyebrow">CASE {level+1} COMPLETE</p><h1>{all?"Room cleared!":"Time’s up!"}</h1><div className="paws">{[1,2,3].map(n=><span key={n} className={n<=paws?"earned":""}>🐾</span>)}</div><p className="result-line">You found <b>{found.length} of 5</b> hazards · <b>{score.toLocaleString()}</b> points</p><div className="safety"><b>⚡ A note from Oggi</b><p>Spotting a possible hazard is the first step. Electrical repairs should be performed by a qualified electrician.</p></div>{all?<button className="primary" onClick={finish}>{level===4?"See My Results":"Continue the Casebook"} →</button>:<button className="primary" onClick={()=>begin(level)}>Try This Room Again ↻</button>}<button className="secondary">Something Look Wrong at Home?</button></main>}
 if(screen==="final")return <main className="final"><div className="share-card"><div className="brand">GEN<span>3</span> <small>× OGGI</small></div><Oggi mood="jump"/><p className="eyebrow">PHILLY HAZARD HUNT</p><h1>“I found 5 out of 5 electrical hazards with Oggi!”</h1><div className="score-box"><span>FINAL SCORE<b>{score.toLocaleString()}</b></span><span>BADGE<b>{badge}</b></span></div><div className="paw-trail">🐾　🐾　🐾</div></div><button className="primary" onClick={()=>navigator.share?.({title:"Oggi’s Electrical Hazard Hunt",text:"I found 5 out of 5 electrical hazards with Oggi! Can you?",url:location.href})}>Challenge a Friend ↗</button><button className="text-btn" onClick={()=>setScreen("map")}>Play again</button><p className="fine">For fun and awareness only. This game is not an inspection of your home.</p></main>;
 return <main className="game-shell"><header className="hud"><button aria-label="Exit" onClick={()=>setScreen("map")}>×</button><div className="case"><small>CASE {level+1} OF 5</small><b>{active.name}</b></div><div className={`timer ${time<16?"low":""}`}>⏱ <b>{Math.floor(time/60)}:{String(time%60).padStart(2,"0")}</b></div><div className="found-count"><b>{found.length}/5</b><small>FOUND</small></div><button aria-label="Toggle sound" onClick={()=>setSound(!sound)}>{sound?"♪":"♩"}</button><button aria-label="Pause" onClick={()=>setPaused(!paused)}>{paused?"▶":"Ⅱ"}</button></header>
 <section className="play-area"><div className="stage-wrap"><div className="stage" ref={stage} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} onWheel={e=>{e.preventDefault();setScale(s=>Math.max(1,Math.min(2,s+(e.deltaY<0?.15:-.15))))}} style={{transform:`translate(${offset.x}px,${offset.y}px) scale(${scale})`}}><img src={active.image} alt={`Illustrated ${active.name}`}/>{active.items.map(item=><button key={item.id} aria-label={`Inspect ${item.name}`} className={`hotspot ${item.kind} ${found.includes(item.id)?"solved":""}`} style={{left:item.x+"%",top:item.y+"%"}} onPointerDown={e=>e.stopPropagation()} onClick={()=>inspect(item)}><span>{found.includes(item.id)?"✓":""}</span></button>)}<i className="hint-ring"/></div></div><div className="zoom"><button onClick={()=>setScale(s=>Math.max(1,s-.25))}>−</button><span>{Math.round(scale*100)}%</span><button onClick={()=>setScale(s=>Math.min(2,s+.25))}>+</button></div><div className="oggi-dock"><Oggi mood={mood}/><div className="speech">{time<16&&!message?"Ruff! Time’s running out!":message?message.split("|")[0]:"Sniff around. Tap anything suspicious!"}</div></div><button className="hint-btn" onClick={hint} disabled={!hints}>🐾 Oggi Hint <b>{hints}</b></button></section>
 {message&&<div className="discovery-backdrop"><div role="dialog" aria-modal="true" aria-labelledby="discovery-title" className={`discovery ${message.startsWith("Oggi's")?"hint-note":""}`}>{message.split("|")[2]&&selectedItem&&<div className="hazard-closeup"><div className="magnified-scene" role="img" aria-label={`Magnified view of ${selectedItem.name}`} style={{backgroundImage:`url(${active.image})`,backgroundPosition:`${selectedItem.x}% ${selectedItem.y}%`}}><span>⌕</span></div><small>MAGNIFIED CLUE</small></div>}<div className="discovery-top"><span>{message.split("|")[2]?"⚡ HAZARD FOUND":"🐾 OGGI SAYS"}</span><b id="discovery-title">{message.split("|")[0]}</b></div><p className="plain">{message.split("|")[1]}</p>{message.split("|")[2]&&<><div className="detail"><strong>Why it matters</strong><p>{message.split("|")[2]}</p></div><div className="next-step"><strong>What should you do?</strong><p>Don’t touch or attempt a repair. Stop using the item if you can do so safely, keep people away, and contact a qualified electrician.</p></div></>}<button className="primary discovery-continue" onClick={closeMessage}>{found.length===5&&message.split("|")[2]?"Finish the Room":"Keep Looking"} →</button></div></div>}{paused&&<div className="pause"><Oggi mood="hiding"/><h2>Case paused</h2><button className="primary" onClick={()=>setPaused(false)}>Keep Sniffing</button><button className="text-btn" onClick={()=>begin(level)}>Restart room</button></div>}</main>;
}
